# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first-screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1000, 700)
        mainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(96, 129, 240, 255), stop:0.55 rgba(61, 225, 235, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"color:white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(260, 150, 480, 45))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.mainLabel.setFont(font)
        self.mainLabel.setStyleSheet("background:transparent;\n"
"font-size:30px;")
        self.mainLabel.setObjectName("mainLabel")
        self.UploadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.UploadBtn.setGeometry(QtCore.QRect(370, 310, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.UploadBtn.setFont(font)
        self.UploadBtn.setObjectName("UploadBtn")
        self.UploadBtn.clicked.connect(
            lambda: self.UploadButtonFunction(mainWindow))
        self.queryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.queryBtn.setGeometry(QtCore.QRect(370, 380, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.queryBtn.setFont(font)
        self.queryBtn.setObjectName("queryBtn")
        self.queryBtn.clicked.connect(
            lambda: self.QueryButtonFunction(mainWindow))
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Welcome"))
        self.mainLabel.setText(_translate("mainWindow", "Video Question Answer System"))
        self.UploadBtn.setText(_translate("mainWindow", "Upload Video"))
        self.queryBtn.setText(_translate("mainWindow", "Ask Query"))

    def QueryButtonFunction(self, mainWindow):

        from GUI1 import Ui_MainWindow
        import sys
        global subWindow
        subWindow = QtWidgets.QMainWindow()
        lui = Ui_MainWindow()
        lui.setupUi(subWindow)
        mainWindow.close()
        subWindow.show()

    def UploadButtonFunction(self, mainWindow):

        from UploadFile import UploadUi_MainWindow
        global subWindow
        subWindow = QtWidgets.QMainWindow()
        lui = UploadUi_MainWindow()
        lui.setupUi(subWindow)
        mainWindow.close()
        subWindow.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
