# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from UserInput import ConvertingVoiceToTxt , RecordUserVoice
from FetchData import  FetchingRecords

class Ui_MainWindow(object):

    def __init__(self):
        self.InputValue = ""


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(96, 129, 240, 255), stop:0.55 rgba(61, 225, 235, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"color:white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ProjectNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProjectNameLabel.setGeometry(QtCore.QRect(240, 80, 700, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ProjectNameLabel.setFont(font)
        self.ProjectNameLabel.setStyleSheet("background:transparent;")
        self.ProjectNameLabel.setObjectName("ProjectNameLabel")
        self.NextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NextBtn.setGeometry(QtCore.QRect(470, 390, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.NextBtn.setFont(font)
        self.NextBtn.setObjectName("NextBtn")
        self.NextBtn.clicked.connect(
            lambda: self.RecordButtonFunction())
        self.inputLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel.setGeometry(QtCore.QRect(240, 210, 420, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputLabel.setFont(font)
        self.inputLabel.setStyleSheet("background:transparent;")
        self.inputLabel.setObjectName("inputLabel")
        self.Query_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Query_input.setGeometry(QtCore.QRect(240, 280, 491, 45))
        self.Query_input.setStyleSheet("background:transparent;\n"
"font-size:18px;\n"                                    
"border:1px solid white;")
        self.Query_input.setObjectName("Query_input")
        self.SearchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SearchBtn.setGeometry(QtCore.QRect(390, 490, 211, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SearchBtn.setFont(font)
        self.SearchBtn.setObjectName("SearchBtn")
        self.SearchBtn.clicked.connect(
            lambda: self.SearchButtonFunction(MainWindow))
        self.inputLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel_2.setGeometry(QtCore.QRect(240, 390, 231, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputLabel_2.setFont(font)
        self.inputLabel_2.setStyleSheet("background:transparent;")
        self.inputLabel_2.setObjectName("inputLabel_2")
        self.backLink = QtWidgets.QPushButton(self.centralwidget)
        self.backLink.setGeometry(QtCore.QRect(460, 560, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.backLink.setFont(font)
        self.backLink.setStyleSheet("background:transparent;\n"
"border:none;")
        self.backLink.setObjectName("backLink")
        self.backLink.clicked.connect(
            lambda: self.backButtonFunction(MainWindow))
        self.ORlabel = QtWidgets.QLabel(self.centralwidget)
        self.ORlabel.setGeometry(QtCore.QRect(480, 330, 51, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ORlabel.setFont(font)
        self.ORlabel.setStyleSheet("background:transparent;")
        self.ORlabel.setObjectName("ORlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ProjectNameLabel.setText(_translate("MainWindow", "Video Question Answer System"))
        self.NextBtn.setText(_translate("MainWindow", "Record"))
        self.inputLabel.setText(_translate("MainWindow", "Input From Keyboard"))
        self.SearchBtn.setText(_translate("MainWindow", "Search"))
        self.inputLabel_2.setText(_translate("MainWindow", "Input From Mice"))
        self.backLink.setText(_translate("MainWindow", "Go Back"))
        self.ORlabel.setText(_translate("MainWindow", "OR"))


    def RecordButtonFunction(self):
        # self.ORlabel.clear()
        # self.ORlabel.setText("Recording ................")
        RecordUserVoice()
        recordedInput = ConvertingVoiceToTxt()
        self.Query_input.setText(recordedInput)

    def SearchButtonFunction(self, MainWindow):
        inp = str(self.Query_input.text())
        if inp != "":
            Doclist = []
            List = FetchingRecords(inp)
            Doclist = List
            print("results ",Doclist)
            if len(Doclist) == 0 :
                from dialogueBox import Ui_MainWindow
                global msgWindow
                msgWindow = QtWidgets.QMainWindow()
                lui = Ui_MainWindow("No Matching Results Found !!!")
                lui.setupUi(msgWindow)
                msgWindow.show()
            else:
                print("GUI2")
                from GUI2 import Ui_SubWindow
                global subWindow
                subWindow = QtWidgets.QMainWindow()
                lui = Ui_SubWindow(Doclist)
                lui.setupUi(subWindow)
                MainWindow.close()
                subWindow.show()
        else:
            from dialogueBox import Ui_MainWindow
            global msgWindow2
            msgWindow2 = QtWidgets.QMainWindow()
            lui = Ui_MainWindow("Type or Record Your Query !!!")
            lui.setupUi(msgWindow2)
            msgWindow2.show()

    def backButtonFunction(self, mainWindow):
        from firstScreen import Ui_mainWindow
        global subWindow
        subWindow = QtWidgets.QMainWindow()
        lui = Ui_mainWindow()
        lui.setupUi(subWindow)
        mainWindow.close()
        subWindow.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
